name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: backend/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('backend/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        run: |
          cd backend
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env.example to .env
        run: cp backend/.env.example backend/.env

      - name: Set permissions
        run: |
          cd backend
          chmod -R 777 storage bootstrap/cache

      - name: Generate Laravel key
        run: cd backend && php artisan key:generate

      - name: Wait for MySQL
        run: |
          sudo apt-get install -y mysql-client
          for i in {1..15}; do
            if mysql -h127.0.0.1 -ularavel -psecret -e "SELECT 1"; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Run migrations
        run: cd backend && php artisan migrate --force

      - name: Run tests
        run: cd backend && php artisan test
